"""Block-art piece sprites for the big board sizes (pure data plus a pixel classifier).

Each sprite is a square bitmap, one string per pixel row, ``size`` pixels wide and tall. A board
square of a sprite size is ``size`` columns by ``size // 2`` rows: every terminal cell shows two
vertically stacked pixels with an upper-half block, and since a cell is about twice as tall as it
is wide the pixels come out square.

Pixel legend:

    .   transparent: the square colour shows through
    o   the piece's fill (light for White, very dark for Black)
    #   the piece's outline (dark for White, light grey for Black)
    x   a detail line inside the piece, drawn in the outline colour

The two biggest sizes are outlined drawings; the small ones are solid silhouettes with detail
lines, because a one-pixel outline would eat most of a tiny piece. Detail pixels are kept apart
from outline pixels so that a colour-less board can leave them blank inside a solid Black piece.
Every sprite keeps its bottom pixel row empty, so pieces on vertically adjacent squares never
touch.
"""

from __future__ import annotations

from typing import Dict, Tuple

EMPTY, FILL, LINE, DETAIL = 0, 1, 2, 3

Grid = Tuple[Tuple[int, ...], ...]

ART: Dict[int, Dict[str, Tuple[str, ...]]] = {
    8: {
        "K": (
            "...oo...",
            "..oooo..",
            "...oo...",
            ".oooooo.",
            "..oooo..",
            "..xxxx..",
            ".oooooo.",
            "........",
        ),
        "Q": (
            "...oo...",
            ".o.oo.o.",
            ".oooooo.",
            "..oooo..",
            "..xxxx..",
            "..oooo..",
            ".oooooo.",
            "........",
        ),
        "R": (
            "........",
            ".o.oo.o.",
            ".oooooo.",
            "..oooo..",
            "..oooo..",
            ".xxxxxx.",
            ".oooooo.",
            "........",
        ),
        "B": (
            "...oo...",
            "..ooxo..",
            "..oxoo..",
            "..oooo..",
            "...oo...",
            "..xxxx..",
            ".oooooo.",
            "........",
        ),
        "N": (
            "....o.o.",
            "...oooo.",
            "..ooxoo.",
            ".oooooo.",
            ".oo.ooo.",
            "...oooo.",
            ".oooooo.",
            "........",
        ),
        "P": (
            "........",
            "........",
            "...oo...",
            "..oooo..",
            "...oo...",
            "..oooo..",
            ".oooooo.",
            "........",
        ),
    },
    10: {
        "K": (
            "....oo....",
            "...oooo...",
            "....oo....",
            ".oo.oo.oo.",
            ".oooooooo.",
            "..oooooo..",
            "..xxxxxx..",
            "...oooo...",
            ".oooooooo.",
            "..........",
        ),
        "Q": (
            "....oo....",
            ".o..oo..o.",
            ".oo.oo.oo.",
            ".oooooooo.",
            "..oooooo..",
            "...oooo...",
            "..xxxxxx..",
            "...oooo...",
            ".oooooooo.",
            "..........",
        ),
        "R": (
            "..........",
            ".oo.oo.oo.",
            ".oooooooo.",
            ".xxxxxxxx.",
            "..oooooo..",
            "..oooooo..",
            "..oooooo..",
            ".xxxxxxxx.",
            ".oooooooo.",
            "..........",
        ),
        "B": (
            "....oo....",
            "...oooo...",
            "..oooxoo..",
            "..ooxooo..",
            "..oooooo..",
            "...oooo...",
            "..xxxxxx..",
            "...oooo...",
            ".oooooooo.",
            "..........",
        ),
        "N": (
            ".....o.o..",
            "....oooo..",
            "...ooxooo.",
            "..ooooooo.",
            ".oooooooo.",
            ".oo..oooo.",
            ".....oooo.",
            "..xxxxxx..",
            ".oooooooo.",
            "..........",
        ),
        "P": (
            "..........",
            "..........",
            "....oo....",
            "...oooo...",
            "...oooo...",
            "....oo....",
            "...oooo...",
            "..oooooo..",
            ".oooooooo.",
            "..........",
        ),
    },
    12: {
        "K": (
            ".....oo.....",
            "....oooo....",
            ".....oo.....",
            "..oo.oo.oo..",
            ".oooooooooo.",
            ".oooooooooo.",
            "..oooooooo..",
            "..xxxxxxxx..",
            "...oooooo...",
            "..oooooooo..",
            ".oooooooooo.",
            "............",
        ),
        "Q": (
            ".....oo.....",
            ".o...oo...o.",
            ".oo.oooo.oo.",
            ".oooooooooo.",
            "..oooooooo..",
            "...oooooo...",
            "...oooooo...",
            "..xxxxxxxx..",
            "...oooooo...",
            "..oooooooo..",
            ".oooooooooo.",
            "............",
        ),
        "R": (
            "............",
            ".oo..oo..oo.",
            ".oo..oo..oo.",
            ".oooooooooo.",
            ".xxxxxxxxxx.",
            "..oooooooo..",
            "..oooooooo..",
            "..oooooooo..",
            ".xxxxxxxxxx.",
            ".oooooooooo.",
            ".oooooooooo.",
            "............",
        ),
        "B": (
            ".....oo.....",
            "....oooo....",
            ".....oo.....",
            "....oooo....",
            "...oooxoo...",
            "...ooxooo...",
            "...oxoooo...",
            "....oooo....",
            "..xxxxxxxx..",
            "...oooooo...",
            ".oooooooooo.",
            "............",
        ),
        "N": (
            "............",
            "......o.oo..",
            ".....ooooo..",
            "....ooxoooo.",
            "...oooooooo.",
            "..ooooooooo.",
            ".oooooooooo.",
            ".ooo.oooooo.",
            ".....oooooo.",
            "..xxxxxxxx..",
            ".oooooooooo.",
            "............",
        ),
        "P": (
            "............",
            "............",
            "............",
            ".....oo.....",
            "....oooo....",
            "....oooo....",
            ".....oo.....",
            "....oooo....",
            "...oooooo...",
            "..oooooooo..",
            ".oooooooooo.",
            "............",
        ),
    },
    14: {
        "K": (
            ".....####.....",
            ".....#oo#.....",
            "...###oo###...",
            "...#oooooo#...",
            "..####oo####..",
            ".#ooo#oo#ooo#.",
            ".#oooooooooo#.",
            ".#oooooooooo#.",
            "..#oooooooo#..",
            "...#oooooo#...",
            "..##########..",
            "..#oooooooo#..",
            "..##########..",
            "..............",
        ),
        "Q": (
            "..............",
            "......##......",
            "..#..#oo#..#..",
            ".#o#..##..#o#.",
            ".#oo##oo##oo#.",
            "..#oooooooo#..",
            "..#oooooooo#..",
            "...#oooooo#...",
            "...#oooooo#...",
            "....#oooo#....",
            "..##########..",
            "..#oooooooo#..",
            "..##########..",
            "..............",
        ),
        "R": (
            "..............",
            "..............",
            ".###.####.###.",
            ".#o#.#oo#.#o#.",
            ".#o###oo###o#.",
            ".#oooooooooo#.",
            ".############.",
            "..#oooooooo#..",
            "..#oooooooo#..",
            "..#oooooooo#..",
            ".############.",
            ".#oooooooooo#.",
            ".############.",
            "..............",
        ),
        "B": (
            "..............",
            "......##......",
            ".....#oo#.....",
            "......##......",
            ".....#oo#.....",
            "....#ooox#....",
            "...#oooxoo#...",
            "...#ooxooo#...",
            "...#oooooo#...",
            "....#oooo#....",
            "..##########..",
            "..#oooooooo#..",
            "..##########..",
            "..............",
        ),
        "N": (
            "..............",
            "......#.##....",
            ".....#o#oo#...",
            "....#oooooo#..",
            "...#ooxooooo#.",
            "..#ooooooooo#.",
            ".#oooooooooo#.",
            ".#oo##oooooo#.",
            "..##.#ooooo#..",
            "....#oooooo#..",
            "..##########..",
            "..#oooooooo#..",
            "..##########..",
            "..............",
        ),
        "P": (
            "..............",
            "..............",
            "..............",
            ".....####.....",
            "....#oooo#....",
            "...#oooooo#...",
            "...#oooooo#...",
            "....#oooo#....",
            "....######....",
            "....#oooo#....",
            "...########...",
            "...#oooooo#...",
            "...########...",
            "..............",
        ),
    },
    16: {
        "K": (
            "......####......",
            "......#oo#......",
            "....###oo###....",
            "....#oooooo#....",
            "....###oo###....",
            "......#oo#......",
            "..###.#oo#.###..",
            ".#ooo##oo##ooo#.",
            ".#oooooooooooo#.",
            "..#oooooooooo#..",
            "...##########...",
            "....#oooooo#....",
            "...##########...",
            "..#oooooooooo#..",
            "..############..",
            "................",
        ),
        "Q": (
            "................",
            ".......##.......",
            "..#...#oo#...#..",
            ".#o#...##...#o#.",
            ".#oo#.#oo#.#oo#.",
            "..#oo#oooo#oo#..",
            "..#oooooooooo#..",
            "...#oooooooo#...",
            "...#oooooooo#...",
            "...##########...",
            "....#oooooo#....",
            "...#oooooooo#...",
            "..############..",
            "..#oooooooooo#..",
            "..############..",
            "................",
        ),
        "R": (
            "................",
            "................",
            "................",
            "..###.####.###..",
            "..#o#.#oo#.#o#..",
            "..#o###oo###o#..",
            "..#oooooooooo#..",
            "..############..",
            "...#oooooooo#...",
            "...#oooooooo#...",
            "...#oooooooo#...",
            "...#oooooooo#...",
            "..############..",
            "..#oooooooooo#..",
            "..############..",
            "................",
        ),
        "B": (
            "................",
            ".......##.......",
            "......#oo#......",
            ".......##.......",
            "......#oo#......",
            ".....#oooo#.....",
            "....#ooooox#....",
            "....#ooooxo#....",
            "....#oooxoo#....",
            ".....#oooo#.....",
            "....########....",
            ".....#oooo#.....",
            "...##########...",
            "..#oooooooooo#..",
            "..############..",
            "................",
        ),
        "N": (
            "................",
            "................",
            ".......#.##.....",
            "......#o#oo#....",
            ".....#oooooo#...",
            "....#ooxooooo#..",
            "...#oooooooooo#.",
            "..#ooooooooooo#.",
            ".#ooo##ooooooo#.",
            ".#oo#.#oooooo#..",
            "..##..#oooooo#..",
            ".....#ooooooo#..",
            "..############..",
            "..#oooooooooo#..",
            "..############..",
            "................",
        ),
        "P": (
            "................",
            "................",
            "................",
            "......####......",
            ".....#oooo#.....",
            "....#oooooo#....",
            "....#oooooo#....",
            ".....#oooo#.....",
            "....########....",
            ".....#oooo#.....",
            ".....#oooo#.....",
            "....#oooooo#....",
            "...##########...",
            "...#oooooooo#...",
            "...##########...",
            "................",
        ),
    },
}

SIZES: Tuple[int, ...] = tuple(sorted(ART))

_KINDS = {".": EMPTY, "o": FILL, "#": LINE, "x": DETAIL}
_CACHE: Dict[Tuple[int, str], Grid] = {}


def pixels(size: int, piece: str) -> Grid:
    """The pixel grid of ``piece`` (K, Q, R, B, N or P, either case) as EMPTY/FILL/LINE/DETAIL values."""
    key = (size, piece.upper())
    grid = _CACHE.get(key)
    if grid is None:
        grid = _CACHE[key] = tuple(tuple(_KINDS[char] for char in row) for row in ART[size][key[1]])
    return grid
